package com.example.MQTT2SSE_BackEnd;

import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.integration.annotation.ServiceActivator;
import org.springframework.integration.channel.DirectChannel;
import org.springframework.integration.core.MessageProducer;
import org.springframework.integration.mqtt.core.DefaultMqttPahoClientFactory;
import org.springframework.integration.mqtt.core.MqttPahoClientFactory;
import org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter;
import org.springframework.integration.mqtt.outbound.MqttPahoMessageHandler;
import org.springframework.integration.mqtt.support.DefaultPahoMessageConverter;
import org.springframework.integration.mqtt.support.MqttHeaders;
import org.springframework.messaging.*;

@Configuration
public class MqttBeans {

    public MqttPahoClientFactory mqttClientFactory() {
        DefaultMqttPahoClientFactory factory = new DefaultMqttPahoClientFactory();
        MqttConnectOptions options = new MqttConnectOptions();

        options.setServerURIs(new String[] {"tcp://159.69.51.171:1883"});
        options.setUserName("terso");
        String password = "2OU5GZSB04ocdsjNDTxsK";
        options.setPassword(password.toCharArray());
        options.setAutomaticReconnect(false); //TODO: change to true
        options.setCleanSession(true);
        options.setConnectionTimeout(10);
        String willMsg = "Client disconnected ungracefully";
        options.setWill("failTopic", willMsg.getBytes(), 2, false);

        factory.setConnectionOptions(options); //Mqtt connection options injected into factory

        return factory;
    }

    //Channel for subscribing
    @Bean
    public MessageChannel mqttInputChannel() {
        //A channel that invokes a single subscriber for each sent Message.
        //The invocation will occur in the sender's thread.
        return new DirectChannel(); //the connection is point 2 point
    }

    @Bean
    public MessageProducer inBound() {
        //Topics for which the ChannelAdapter keeps listening on are only the ones in the context
        //TODO Far prendere la lista dei Topics da un file di configurazione
        MqttPahoMessageDrivenChannelAdapter adapter = new MqttPahoMessageDrivenChannelAdapter("GabrieleBEServer",
                mqttClientFactory(), "/floud/autocounter/diag/#");
        adapter.setCompletionTimeout(5000);
        //By default, the default DefaultPahoMessageConverter produces a message with a String payload
        // with the following headers: (mqtt_topic, mqtt_duplicate, mqtt_qos)
        adapter.setConverter(new DefaultPahoMessageConverter());
        adapter.setQos(0);
        adapter.setOutputChannel(mqttInputChannel());

        return adapter;
    }

    @Bean
    @ServiceActivator(inputChannel = "mqttInputChannel")
    public MessageHandler handler() {
        return new MessageHandler() {
            @Override
            public void handleMessage(Message message) throws MessagingException {
                String topic = message.getHeaders().get(MqttHeaders.RECEIVED_TOPIC).toString();
                /*if (topic.equals("newentry")) {
                    System.out.println("New Entry Topic Event");
                }*/
                System.out.println(message.getPayload());
                String payload = message.getPayload().toString();
                //System.out.println("Retained: " + message.getHeaders().get(MqttHeaders.RECEIVED_RETAINED));
                // System.out.println(msg);
                //NewsSSEController nssec = new NewsSSEController();
                try {
                    SseController.dispatchEventsToClients(topic, payload);
                    //SseController.addStatusMessage(topic, payload);
                    SseController.addStatusMessage(topic, new StatusMessage(payload));
                    //SseController.addStatusMessage("/floud/autocounter/diag/", payload);
                } catch (MessageHandlingException mhe) {
                    System.out.println("Message Handling Error");
                    mhe.printStackTrace();
                }

            }
        };
    }


    //Channel for publishing
    @Bean
    public MessageChannel mqttOutboundChannel() {
        return new DirectChannel();
    }

    @Bean
    @ServiceActivator(inputChannel = "mqttOutboundChannel")
    public MessageHandler mqttOutbound() {
        MqttPahoMessageHandler messageHandler = new MqttPahoMessageHandler("serverOut", mqttClientFactory());

        //When async and async-events are both true, an MqttMessageSentEvent is emitted (See Events).
        //It contains the message, the topic, the messageId generated by the client library, the clientId,
        // and the clientInstance (incremented each time the client is connected).
        messageHandler.setAsync(true); //to let always listen the channel
        messageHandler.setAsyncEvents(true);
        messageHandler.setDefaultTopic("#");
        return messageHandler;
    }

}
